Add support for gitlab
jemc/pony-stable pull request #69
Opened 2018-06-14 14:32 UTC by ii8

2018-06-14 15:05 UTC, SeanTAllen commented
This looks good to me. @jemc any comments before I merge?

2018-06-14 15:06 UTC, SeanTAllen approved these changes

2018-06-14 15:06 UTC, SeanTAllen commented
Thanks @ii8. Nice first contribution to stable.

2018-06-14 15:39 UTC, srenatus approved these changes
LGTM 😃

2018-06-14 15:40 UTC, srenatus commented
We'll have to get #57 and #67 updated when this is in, but that's fine 👍

2018-06-14 16:30 UTC, jemc requested changes

2018-06-14 16:30 UTC, jemc commented on stable/dep.pony
> +  new create(d: String, b: Bundle box, i: JsonObject box) ? =>
Small change, but I'd prefer the parameter signature to put the new parameter at the end:
```pony
create(b: Bundle box, i: JsonObject box, d: String)
```

This keeps consistency a bit better with the other `Dep` types, which all take `b: Bundle box, i: JsonObject box` as their first two arguments.

2018-06-15 12:50 UTC, mfelsche commented
@jemc seems your issue has been resolved. we cool to mege now?

2018-06-15 12:56 UTC, jemc approved these changes

2018-06-15 12:57 UTC, merged